### ISSUE TITLE
Problem with MEAN recipe and MySQL : mysqlCli is not defined

### ISSUE THREAD

**Issue by clementbirkle** [lando/mean#2]
Hello,

I tried to build Lando (3.6.1) with this file (.lando.yml):

```
name: test
recipe: mean
config:
  #node: 12
  build:
    - npm install
  database: mysql
  globals:
    npx: latest
  port: '8055'
  ssl: true
  config:
    #database: ../config/my-custom.cnf
    #php: ../config/php.ini
    #server: ../config/httpd.conf
    #vhosts: ../config/default-ssl.conf
services:
  appserver:
    build_as_root:
      #-npm install -g npx
  phpmyadmin:
    type: phpmyadmin
  mailhog:
    type: mailhog
tooling:
  npx:
    service: appserver
```

and I got this error:

```
Unhandled rejection ReferenceError: mysqlCli is not defined
    at Object.getDbTooling (/snapshot/cli/node_modules/@lando/mean/lib/utils.js)
    at getTooling (/snapshot/cli/node_modules/@lando/mean/recipes/mean/builder.js)
    at new LandoMean (/snapshot/cli/node_modules/@lando/mean/recipes/mean/builder.js)
    at AsyncEvents.<anonymous> (/snapshot/cli/plugins/lando-recipes/app.js)
    at AsyncEvents.handle (/snapshot/cli/lib/events.js)
    at /snapshot/cli/lib/events.js
    at processImmediate (internal/timers.js:464:21)
From previous event:
    at AsyncEvents.emit (/snapshot/cli/lib/events.js)
    at /snapshot/cli/lib/app.js
From previous event:
    at App.init (/snapshot/cli/lib/app.js)
    at /snapshot/cli/bin/lando.js
From previous event:
    at Object.<anonymous> (/snapshot/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1751:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.runMain (pkg/prelude/bootstrap.js:1804:12)
    at internal/main/run_main_module.js:17:47
```
If I try with Mongodb, it works well.

Thank you for your help.
